# Generated by Django 2.2.5 on 2019-11-06 02:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adobe_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentbox',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 5, 19, 30, 29, 303498), verbose_name='Date of Entry'),
        ),
    ]
